### ISSUE TITLE
Establish someone to receive alerts about new issues

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/breastPhantom#2]
Who is receiving these?
Please update accordingly.

**Comment by brandon-gallas** [comment]
Diksha, you said you are now monitoring this. Please confirm by closing this issue.

**Comment by diksha-s** [comment]
Yes, I am getting notified now.  But not getting option to close the issue.

**Comment by brandon-gallas** [comment]
I gave you admin responsibilities for this repo. Do you see the close button now? If not, let's do a quick teams chat.

B
